baseURL: 'https://blog.neugartf.com/'
languageCode: en-us
title: Hellow.
theme: PaperMod
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  showCodeCopyButtons: true
  homeInfoParams:
    Title: Hi there 👋
    Content: I'm Fabian Neugart. Welcome to my blog!
  socialIcons:
    - name: mastodon
      url: "https://mastodon.green/@ngt"
    - name: twitter
      url: "https://mobile.twitter.com/_ngt__"
    - name: github
      url: "https://github.com/neugartf"
  ShowCodeCopyButtons: true
  GoatCounterCode: "neugartf"
