backend:
    name: git-gateway
    branch: master
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/posts"
    identifier_field: name
    create: true
    nested:
      depth: 2
    fields: # The fields for each document, usually in front matter
        - {label: "Path", name: "path", widget: "string"}
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Publish Date", name: "date", widget: "datetime"}
        - {label: "Description", name: "description", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}
